--- #YAML:1.0
name:                PDF-Table
version:             0.9.5
abstract:            A utility class for building table layouts in a PDF::API2 object.
license:             ~
author:              
    - Desislav Kamenov <desi@vratza.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
